spring.application.name=session-auth

# 쿠키 이름 SID 로 설정
server.servlet.session.cookie.name=SID
# JS에서 쿠키 못 읽게 함 => XSS 탈취 방어
server.servlet.session.cookie.http-only=true
# 교차 사이트 요청시 쿠키 안 붙임
server.servlet.session.cookie.same-site=lax

# 세션 만료 시간 30분
server.servlet.session.timeout=30m